[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Ivan Kiselev <kiselev_ivan@pm.me>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/homelessnessbo/wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
